"""Build MulVAL input programs from an abstract LLM_MTD_emo topology model."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


ATOM_PATTERN = re.compile(r"^[a-z][A-Za-z0-9_]*$")


def prolog_atom(value):
    """Render a Python value as a conservative Prolog atom."""
    if isinstance(value, (int, float)):
        return str(value)

    text = str(value)
    if ATOM_PATTERN.match(text):
        return text
    escaped = text.replace("\\", "\\\\").replace("'", "\\'")
    return f"'{escaped}'"


def fact(predicate, *values):
    rendered_values = ", ".join(prolog_atom(value) for value in values)
    return f"{predicate}({rendered_values})."


def comment(text):
    return f"% {text}"


def render_mulval_program(model, scenario_id=None, attack_goal=None):
    """Return a MulVAL .P program for the provided abstract topology model."""
    scenario_id = scenario_id or model.get("scenario_id") or "auto_full_topology"
    attack_goal = attack_goal or model.get("attack_goal") or {
        "predicate": "execCode",
        "host": "cloud_db",
        "privilege": "root",
    }

    lines = [
        comment("Generated by LLM_MTD_emo MulVAL integration."),
        comment(f"scenario_id: {scenario_id}"),
        comment("Standard MulVAL facts are followed by project annotations."),
        "",
    ]
    lines.extend(_render_hosts(model))
    lines.extend(_render_connectivity(model))
    lines.extend(_render_weaknesses(model))
    lines.extend(_render_entry_points(model))
    lines.extend(_render_attack_goal(attack_goal))
    lines.extend(_render_annotations(model, scenario_id))
    return "\n".join(lines).rstrip() + "\n"


def _render_hosts(model):
    lines = [comment("Hosts")]
    for host in model.get("hosts", []):
        host_id = host["id"]
        lines.append(fact("host", host_id))
        lines.append(fact("hostRole", host_id, host.get("role", "unknown")))
        lines.append(fact("hostLayer", host_id, host.get("layer", "unknown")))
        for ip_address in host.get("ips", []):
            lines.append(fact("hostIp", host_id, ip_address))
    lines.append("")
    return lines


def _render_connectivity(model):
    lines = [comment("Connectivity")]
    for edge in model.get("connectivity", []):
        lines.append(
            fact(
                "hacl",
                edge["src"],
                edge["dst"],
                edge.get("protocol", "tcp"),
                int(edge.get("port", 8000)),
            )
        )
        lines.append(
            fact(
                "connectivityReason",
                edge["src"],
                edge["dst"],
                edge.get("reason", "unspecified"),
            )
        )
    lines.append("")
    return lines


def _render_weaknesses(model):
    lines = [comment("Weakness and service assumptions")]
    seen_properties = set()
    seen_services = set()

    for weakness in model.get("weaknesses", []):
        host = weakness["host"]
        service = weakness["service"]
        service_key = (host, service, weakness.get("protocol", "tcp"), weakness.get("port", 8000))

        if service_key not in seen_services:
            lines.append(
                fact(
                    "networkServiceInfo",
                    host,
                    service,
                    weakness.get("protocol", "tcp"),
                    int(weakness.get("port", 8000)),
                    weakness.get("privilege", "root"),
                )
            )
            seen_services.add(service_key)

        lines.append(fact("vulExists", host, weakness["id"], service))
        lines.append(fact("weakness", host, weakness["id"]))

        if weakness["id"] not in seen_properties:
            lines.append(
                fact(
                    "vulProperty",
                    weakness["id"],
                    weakness.get("exploit_class", "remoteExploit"),
                    weakness.get("impact", "privEscalation"),
                )
            )
            seen_properties.add(weakness["id"])

    lines.append("")
    return lines


def _render_entry_points(model):
    lines = [comment("Attacker entry assumptions")]
    external_attacker_needed = False

    for entry in model.get("entry_points", []):
        entry_id = entry["id"]
        node = entry["node"]
        kind = entry.get("kind", "compromised_host")
        lines.append(fact("entryPoint", entry_id, node))
        lines.append(fact("entryKind", entry_id, kind))

        if kind == "compromised_host":
            lines.append(fact("attackerLocated", node))
        elif kind == "external_service":
            external_attacker_needed = True
            lines.append(
                fact(
                    "hacl",
                    "external",
                    node,
                    entry.get("protocol", "tcp"),
                    int(entry.get("port", 8000)),
                )
            )

    if external_attacker_needed:
        lines.append(fact("host", "external"))
        lines.append(fact("attackerLocated", "external"))

    lines.append("")
    return lines


def _render_attack_goal(attack_goal):
    predicate = attack_goal.get("predicate", "execCode")
    host = attack_goal.get("host", "cloud_db")
    privilege = attack_goal.get("privilege", "root")
    return [
        comment("Attack goal"),
        f"attackGoal({predicate}({prolog_atom(host)}, {prolog_atom(privilege)})).",
        "",
    ]


def _render_annotations(model, scenario_id):
    lines = [comment("Policy-layer annotations")]
    lines.append(fact("scenarioId", scenario_id))
    for target in model.get("critical_targets", []):
        lines.append(fact("criticalTarget", target))
    for rule in model.get("management_visibility", []):
        lines.append(fact("managementVisibility", rule["controller"], rule["target"]))
    lines.append("")
    return lines


def main():
    parser = argparse.ArgumentParser(description="Render a MulVAL .P file from topology JSON.")
    parser.add_argument("model_json", help="Path to abstract topology JSON.")
    parser.add_argument("--output", "-o", required=True, help="Output .P file path.")
    parser.add_argument("--scenario-id", default=None, help="Override scenario id.")
    parser.add_argument("--attack-goal-host", default=None, help="Override attack goal host.")
    parser.add_argument("--attack-goal-privilege", default="root", help="Attack goal privilege.")
    args = parser.parse_args()

    with open(args.model_json, "r", encoding="utf-8") as model_file:
        model = json.load(model_file)

    attack_goal = None
    if args.attack_goal_host:
        attack_goal = {
            "predicate": "execCode",
            "host": args.attack_goal_host,
            "privilege": args.attack_goal_privilege,
        }

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        render_mulval_program(model, scenario_id=args.scenario_id, attack_goal=attack_goal),
        encoding="utf-8",
    )
    print(f"wrote {output_path}")


if __name__ == "__main__":
    main()
